#!/usr/bin/env python3
"""fpgen.py — generate the FP fixed-point conversion classify table.

Single source of truth for the SCVTF/UCVTF/FCVTZS/FCVTZU #fbits forms.
The mask lists formerly lived in three places (interp_fp.cpp,
ir_translate_fp.cpp, jit_translate.cpp) and drifted. Now each op is one
row in a spec file and this script emits a generated header both sides
include, so they cannot diverge.

Usage:
    python3 tools/opgen/fpgen.py tools/opgen/fp_fixconv.txt include/opgen_fpfixed.hpp

Spec format (space/TSV separated, '#' comments, blank lines ignored):
    NAME   MASK         MATCH        FAMILY      IRSUB  [GUARD]
  e.g.
    SCVTF_GPR 0x7F3E0000 0x1E020000  FIXCONV  0  -

MASK is applied to the raw op and the result must equal MATCH. Q/U/size
bit-stripping is folded into MASK/MATCH. GUARD is an optional C++ boolean
expression evaluated with `op` (uint32_t), `Q`, `U`, `size` (uint8_t) in
scope. First match in file order wins, so order rows by priority.

The emitted header defines (namespace arm64emu::fpfixed):
    enum class Family {...};
    struct Op { Family family; uint16_t opc; uint8_t subop; const char* name; };
    Op classify(uint32_t op);
"""
import sys

HEADER = r"""// opgen_fpfixed.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/fpgen.py from tools/opgen/fp_fixconv.txt.
// To add/modify an FP fixed-point conversion opcode edit the spec and
// run: make opgen-fpfixed
//
// Single source of truth for the scaled int<->FP conversions
// (SCVTF/UCVTF/FCVTZS/FCVTZU with #fbits). The interpreter
// (interp_fp.cpp), the IR translator (ir_translate_fp.cpp) and the JIT
// block heuristic (jit_translate.cpp) all classify with
// arm64emu::fpfixed::classify(), so the three copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace fpfixed {

enum class Family : uint8_t {
{FAMILIES}
};

struct Op {
    Family family;
    uint16_t opc;            // stable per-opcode id (row index in spec)
    uint8_t subop;           // per-family semantic sub-opcode (IRSUB)
    const char* name;
};

inline Op classify(uint32_t op) {
    const uint32_t Q    = (op >> 30) & 1u;
    const uint32_t U    = (op >> 29) & 1u;
    const uint32_t size = (op >> 22) & 3u;
    (void)U;
    (void)Q;
    (void)size;
{BODY}
    return Op{Family::UNKNOWN, 0, 0, "unknown"};
}

} // namespace fpfixed
} // namespace arm64emu
"""


def parse_rows(spec_path):
    rows = []
    with open(spec_path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.split('#', 1)[0].strip()
            if not line:
                continue
            toks = line.split()
            if len(toks) < 4:
                print("spec %s:%d: need NAME MASK MATCH FAMILY [IRSUB] [GUARD] (got: %r)"
                      % (spec_path, lineno, line), file=sys.stderr)
                raise SystemExit(2)
            name, mask, match, family = toks[0], toks[1], toks[2], toks[3]
            irsub = int(toks[4], 16) if len(toks) > 4 else 0
            guard_toks = toks[5:] if len(toks) > 5 else []
            guard = ' '.join(guard_toks) if guard_toks else None
            if guard is None or guard.strip() in ('-', ''):
                guard = None
            rows.append((name, mask, match, family, irsub, guard))
    return rows


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    check = '--check' in sys.argv[1:]
    if len(args) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    spec_path, out_path = args
    rows = parse_rows(spec_path)

    fam_order = []
    for r in rows:
        if r[3] not in fam_order:
            fam_order.append(r[3])
    fam_lines = ["    %s = %d," % (f.upper(), i) for i, f in enumerate(fam_order)]
    fam_lines.append("    UNKNOWN = %d," % len(fam_order))

    body_lines = []
    for i, (name, mask, match, family, irsub, guard) in enumerate(rows):
        cond = "(op & 0x%08XU) == 0x%08XU" % (int(mask, 16), int(match, 16))
        if guard:
            cond += " && (%s)" % guard
        body_lines.append("    if (%s) return Op{Family::%s, %d, %d, \"%s\"};"
                          % (cond, family.upper(), i, irsub, name))

    header = (HEADER.replace("{FAMILIES}", "\n".join(fam_lines))
                    .replace("{BODY}", "\n".join(body_lines)))

    if check:
        try:
            cur = open(out_path).read()
        except IOError:
            cur = ""
        if cur != header:
            print("opgen-fpfixed: %s is OUT OF DATE — run `make opgen-fpfixed` "
                  "(spec changed, generated header not synced)" % out_path,
                  file=sys.stderr)
            return 1
        print("opgen-fpfixed: %s is up to date (%d ops)" % (out_path, len(rows)))
        return 0

    with open(out_path, "w") as fh:
        fh.write(header)
    print("wrote %s (%d ops)" % (out_path, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
