#!/usr/bin/env python3
"""glcoverage.py — auto-generate missing core GL (<=3.3) rows for
thunk_dp.txt from the vendored Khronos gl.xml.

Candidate selection (deliberately conservative):
  IN  — commands in gl feature blocks api='gl', number<=3.3, not already
        present in the spec (any GL/GLES row counts as present).
  OUT — functions taking GLdouble/GLclampd BY VALUE ('f' is binary32
        only; doubles need a dedicated arg kind — future work).
  OUT — bulk-buffer pixel paths (COMPSIZE referencing width/height/
        depth or uncomputable): they need real SizeKind policies,
        a 64 KiB default bounce would truncate/overread.
  ARGS— '*' param -> 'p', else 'i'.

The generated block is appended INSIDE marked BEGIN/END comments in the
spec itself (the spec stays the single source of truth;
`make opgen-thunk-check` pins the generated header). --check mode
verifies the marked section byte-matches a fresh generation.
"""
import sys
import os
import xml.etree.ElementTree as ET

SPEC_DEFAULT = 'tools/opgen/thunk_dp.txt'
XML_DEFAULT = 'tools/gl-registry/gl.xml'
MAX_GL_VERSION = 3.3

# Special-case bulk-pixel functions: exact SizeKind specs.
SPECIAL_SIZES = {
    # name: (args, size_kind)
    'glDrawPixels':         ('iiiiz',      'DRAWPIXELS'),
    'glBitmap':             ('iiffffz',    'BITMAP'),
    'glTexImage1D':         ('iiiiiiiz',   'TEXIMAGE1D'),
    'glTexSubImage1D':      ('iiiiiiz',    'TEXSUBIMAGE1D'),
    'glTexSubImage3D':      ('iiiiiiiiiiz','TEXSUBIMAGE3D'),
    'glPolygonStipple':     ('z',          'STIPPLE'),
    'glGetPolygonStipple':  ('z',          'STIPPLE'),
}

BEGIN_MARK = '# ==== BEGIN AUTOGENERATED CORE GL <=3.3 (tools/opgen/glcoverage.py) ===='
END_MARK = '# ==== END AUTOGENERATED CORE GL ===='


def load_spec_names(spec_path):
    """name -> set of families; autogenerated block excluded so
    regeneration re-derives rows purely from gl.xml."""
    names = {}
    in_auto = False
    with open(spec_path) as fh:
        for line in fh:
            if line.startswith('# ==== BEGIN AUTOGENERATED'):
                in_auto = True
                continue
            if line.startswith('# ==== END AUTOGENERATED'):
                in_auto = False
                continue
            if in_auto:
                continue
            line = line.split('#', 1)[0].split()
            if len(line) >= 5 and line[1] in ('GL', 'GLES'):
                names.setdefault(line[0], set()).add(line[1])
    return names


def load_registry(xml_path, api='gl', max_ver=MAX_GL_VERSION):
    """-> ({core command names}, {name: Element})."""
    root = ET.parse(xml_path).getroot()
    core = {}
    for f in root.findall('feature'):
        if f.get('api') != api:
            continue
        try:
            num = float(f.get('number'))
        except ValueError:
            continue
        if num > max_ver:
            continue
        for req in f.findall('require'):
            for e in req.findall('command'):
                core[e.get('name')] = True
    cmds = {}
    for c in root.iter('command'):
        pr = c.find('proto')
        nm = pr.find('name') if pr is not None else None
        if nm is not None and nm.text:
            cmds[nm.text] = c
    return core, cmds


def classify(name, cmd):
    """-> (args, size_kind | '-', skip_reason | None)."""
    ps = cmd.findall('param')
    txts = [''.join(p.itertext()) for p in ps]
    # By-value GLdouble/GLclampd params use the native 'd' kind — EXCEPT
    # when mixed with integer scalars (the THUNK_DOUBLE path is
    # double-only; no mixed i+d ABI support).
    has_byval_d = False
    has_int_scalar = False
    chars = []
    for p, tx in zip(ps, txts):
        if '*' in tx:
            chars.append('p')
        elif 'GLdouble' in tx or 'GLclampd' in tx:
            chars.append('d')
            has_byval_d = True
        else:
            chars.append('i')
            has_int_scalar = True
    if has_byval_d and has_int_scalar:
        return None, '-', 'mixed int+double by value'
    lens = [p.get('len') or '' for p, t in zip(ps, txts)
            if '*' in t]
    if any(('width' in l or 'height' in l or 'depth' in l or l == 'COMPSIZE()')
           for l in lens):
        # The seven bulk-pixel paths have hand-derived SizeKinds — emit
        # them with the exact size spec instead of skipping.
        if name in SPECIAL_SIZES:
            a, sz = SPECIAL_SIZES[name]
            return a, sz, None
        return None, '-', 'bulk pixel buffer needs SizeKind'
    args = ''.join(chars)
    return (args if args else '-'), '-', None


PASSES = [
    # (api, version cap, family column)
    ('gl', MAX_GL_VERSION, 'GL'),
    ('gles2', 3.2, 'GLES'),
]


def generate(xml_path, spec_path):
    """-> ({family: rows}, [(name, reason)])."""
    have = load_spec_names(spec_path)
    all_rows = {}
    skipped = []
    for api, max_ver, fam in PASSES:
        core, cmds = load_registry(xml_path, api, max_ver)
        rows = []
        for name in sorted(core):
            if fam in have.get(name, ()):
                continue
            if name not in cmds:
                skipped.append((name, 'referenced but not defined'))
                continue
            args, szkind, why = classify(name, cmds[name])
            if args is None:
                skipped.append((name, why))
                continue
            rows.append('%-26s %-6s %-13s %-5s %-14s %-6s'
                        % (name, fam, args, '-', '-', szkind))
        all_rows[fam] = rows
    return all_rows, skipped


def main():
    pos = [a for a in sys.argv[1:] if not a.startswith('--')]
    check_only = '--check' in sys.argv[1:]
    spec_path = pos[0] if len(pos) > 0 else SPEC_DEFAULT
    xml_path = pos[1] if len(pos) > 1 else XML_DEFAULT

    all_rows, skipped = generate(xml_path, spec_path)
    total = sum(len(v) for v in all_rows.values())

    def blocks_text():
        out = []
        for _, _, fam in PASSES:
            mk_b = BEGIN_MARK.replace('CORE GL <=3.3',
                                      'CORE %s' % ('GL <=3.3' if fam == 'GL'
                                                   else 'GLES <=3.2'))
            mk_e = END_MARK.replace('CORE GL', 'CORE %s' % fam)
            out.append('\n'.join([mk_b] + all_rows[fam] + [mk_e]))
        return '\n\n'.join(out)

    with open(spec_path) as fh:
        cur = fh.read()
    first_b = BEGIN_MARK.replace('CORE GL <=3.3', 'CORE GL <=3.3')
    last_e = END_MARK.replace('CORE GL', 'CORE GLES')

    if first_b in cur and last_e in cur:
        pre = cur[:cur.index(first_b)]
        post = cur[cur.index(last_e) + len(last_e):]
        old_block = cur[cur.index(first_b):
                        cur.index(last_e) + len(last_e)]
    else:
        pre = cur.rstrip('\n') + '\n\n'
        post = ''
        old_block = None

    new_block = blocks_text()

    if check_only:
        if old_block is None:
            print("glcoverage: no autogenerated block found in", spec_path)
            return 2
        if old_block != new_block:
            import difflib
            diff = list(difflib.unified_diff(
                old_block.splitlines(), new_block.splitlines(),
                'spec', 'regenerated', lineterm=''))
            print('\n'.join(diff[:60]))
            print("glcoverage: autogenerated block DRIFTED")
            return 2
        print("glcoverage: autogenerated block up to date (%d rows)"
              % total)
        return 0

    with open(spec_path, 'w') as fh:
        fh.write(pre + new_block + post)
    print("glcoverage: wrote %d autogenerated rows" % total)
    for name, why in skipped:
        print("  SKIP %-32s (%s)" % (name, why))
    return 0


if __name__ == '__main__':
    sys.exit(main())
