#!/usr/bin/env python3
"""thunkgen.py — generate the thunk symbol signature table.

Single source of truth for "which (library, symbol) is thunked and how to
marshall it". Covers BOTH thunk classes: GraphicThunk (GL/GLES/EGL/SDL/GLFW)
and DisplayThunk (Vulkan/Wayland/X11/XCB/GBM/XShm/GLX/RandR/Xkb). The
hand-written REG_GL*/REG_GLES*/REG_EGL*/REG_SDL*/REG_GLFW* ladders in
thunk.cpp's register_known_symbols_() and the REG_VK*/REG_WL*/REG_X11*/
ladders in display_thunk.cpp's register_known_symbols_(), plus the ad-hoc
`name == ...` special cases in dispatch(), formerly lived as code and
drifted from one another. Now each symbol is one row in a spec file and this
script emits a generated header both sides (registration + dispatch)
include, so they cannot diverge.

Each thunk iterates `specs[]` and registers only the rows whose `lib`
family it owns (GraphicThunk: GL/GLES/EGL/SDL/GLFW; DisplayThunk: the rest).

Usage:
    python3 tools/opgen/thunkgen.py tools/opgen/thunk_dp.txt include/opgen_thunk.hpp

Spec format (whitespace separated, '#' comments, blank lines ignored):
    NAME   LIBS   ARGS...   RET   POLICY   SIZE
  e.g.
    glClear              GL   -          -     -              -
    glBufferData         GL   iizi       -     -              arg1
    glTexImage2D         GL   iiii iiii z  -   -              TEX2D
    glShaderSource       GL   iipp       -     SHADER_SOURCE  -

ARGS is the concatenation of every token between LIBS and RET (so a wide
spec stays readable). RET/POLICY/SIZE are always the final three tokens.
See the spec file header for the full token reference.

ARGS semantics per parameter:
    i  integer/enum register (x-reg) — passed verbatim
    f  IEEE-754 binary32 register (v-reg)
    p  pointer, translated guest→host with writeback
    z  pointer like p, but bounced at a computed size (SIZE column)
ARGS lists the thunk-relevant kinds: a 'p'/'z' at every translated pointer
position and enough 'i' padding to give the right stack arity (n_stack =
len(args) - 8 when len(args) > 8). Trailing 'i's beyond the last pointer
may be elided — the thunk only needs pointer positions + stack arity.

The emitted header defines (namespace arm64emu::thunk):
    enum class LibFamily / Policy / RetKind / SizeKind;
    struct Spec { LibFamily lib; const char* name; const char* args;
                  RetKind ret; Policy policy; SizeKind size; };
    constexpr Spec specs[];  constexpr size_t spec_count;
"""
import sys

VALID_ARGS = set('ifpzd')
VALID_LIBS = ('GL', 'GLES', 'EGL', 'SDL', 'GLFW', 'MIX',
              'VK', 'WL', 'WL_EGL', 'X11', 'X11XCB', 'XCB', 'GBM', 'XEXT',
              'GLX', 'RANDR', 'XKB')
VALID_RET = ('-', 'str')
VALID_POLICY = ('-', 'SHADER_SOURCE', 'QUERY', 'GET_PROC', 'TRACK_TEX',
                'UNTRACK_TEX', 'VA_PTR', 'EL_PTR', 'PRESENT',
                'CURSOR_CB', 'GLFW_POLL', 'KEY_CB', 'MOUSE_CB',
                'FRAMEBUFFER_CB', 'WINDOW_SIZE_CB', 'FOCUS_CB', 'ERROR_CB',
                'GLFW_CREATE',
                'MIX_VERSION', 'MIX_OPEN_AUDIO', 'THREAD_CREATE',
                'THREAD_WAIT',
                'MAP_BUFFER', 'UNMAP_BUFFER', 'FLUSH_BUFFER',
                'TF_VARYINGS',
                'SDL_FREE', 'SDL_OPEN_AUDIO', 'JOY_GUID', 'JOY_GUID_STR',
                'PROXY', 'VULKAN', 'VK_GET_PROC', 'VK_CREATE_INSTANCE',
                'VK_CREATE_DEVICE', 'VK_PRESENT')
VALID_SIZE = ('-', 'arg1', 'arg2', 'TEX2D', 'TEXSUB', 'PITCH_H',
              'READPIXELS', 'QUEUEAUDIO', 'X_DRAWSTR', 'X_SETWMPROTO',
              'TEX3D')

HEADER = r"""// opgen_thunk.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/thunkgen.py from tools/opgen/thunk_dp.txt.
// To add/modify a thunked symbol edit the spec and run: make opgen-thunk
//
// Single source of truth for GraphicThunk (GL/GLES/EGL/SDL/GLFW) AND
// DisplayThunk (Vulkan/Wayland/X11/XCB/GBM/XShm/GLX/RandR/Xkb) registration
// + dispatch. Each thunk's register_known_symbols_() iterates this table
// and registers only the rows whose lib family it owns, and dispatch()
// switches on the per-row POLICY/SIZE/ARGS instead of comparing symbol
// names, so the two copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace thunk {

enum class LibFamily : uint8_t {
{LIBS}
};

enum class Policy : uint8_t {
{POLICIES}
};

enum class RetKind : uint8_t {
    PLAIN = 0,
    STRING = 1,
};

enum class SizeKind : uint8_t {
    NONE = 0,
    ARG1 = 1,
    ARG2 = 2,
    TEX2D = 3,
    TEXSUB = 4,
    PITCH_H = 5,
    READPIXELS = 6,
    QUEUEAUDIO = 7,
    X_DRAWSTR = 8,
    X_SETWMPROTO = 9,
    TEX3D = 10,
};

struct Spec {
    LibFamily   lib;
    const char* name;
    const char* args;       // AAPCS64 kinds per parameter: i/f/p/z, or "" (none)
    RetKind     ret;
    Policy      policy;
    SizeKind    size;
};

inline constexpr Spec specs[] = {
{ROWS}
};

inline constexpr size_t spec_count = sizeof(specs) / sizeof(specs[0]);

} // namespace thunk
} // namespace arm64emu
"""


def parse_rows(spec_path):
    rows = []
    with open(spec_path) as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.split('#', 1)[0].strip()
            if not line:
                continue
            toks = line.split()
            if len(toks) < 6:
                print("spec %s:%d: need NAME LIBS ARGS... RET POLICY SIZE "
                      "(got: %r)" % (spec_path, lineno, line), file=sys.stderr)
                raise SystemExit(2)
            name, lib = toks[0], toks[1]
            ret, policy, size = toks[-3], toks[-2], toks[-1]
            args = ''.join(toks[2:-3])
            if args == '-':
                args = ''
            if lib not in VALID_LIBS:
                print("spec %s:%d: unknown LIBS %r for %s"
                      % (spec_path, lineno, lib, name), file=sys.stderr)
                raise SystemExit(2)
            if any(c not in VALID_ARGS for c in args):
                print("spec %s:%d: bad ARGS token(s) in %r for %s "
                      "(allowed: i f p z d or '-')"
                      % (spec_path, lineno, args, name), file=sys.stderr)
                raise SystemExit(2)
            if ret not in VALID_RET:
                print("spec %s:%d: bad RET %r for %s"
                      % (spec_path, lineno, ret, name), file=sys.stderr)
                raise SystemExit(2)
            if policy not in VALID_POLICY:
                print("spec %s:%d: bad POLICY %r for %s"
                      % (spec_path, lineno, policy, name), file=sys.stderr)
                raise SystemExit(2)
            if size not in VALID_SIZE:
                print("spec %s:%d: bad SIZE %r for %s"
                      % (spec_path, lineno, size, name), file=sys.stderr)
                raise SystemExit(2)
            if size != '-' and 'z' not in args:
                print("spec %s:%d: SIZE %r but no 'z' arg for %s"
                      % (spec_path, lineno, size, name), file=sys.stderr)
                raise SystemExit(2)
            if 'z' in args and size == '-':
                print("spec %s:%d: 'z' arg but SIZE '-' for %s "
                      "(give arg1/arg2/TEX2D/TEXSUB/PITCH_H)"
                      % (spec_path, lineno, name), file=sys.stderr)
                raise SystemExit(2)
            rows.append((name, lib, args, ret, policy, size))
    return rows


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    check = '--check' in sys.argv[1:]
    if len(args) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    spec_path, out_path = args
    rows = parse_rows(spec_path)

    lib_order = []
    for r in rows:
        if r[1] not in lib_order:
            lib_order.append(r[1])
    lib_lines = ["    %s = %d," % (f, i) for i, f in enumerate(lib_order)]
    lib_lines.append("    UNKNOWN = %d," % len(lib_order))

    pol_order = []
    for r in rows:
        p = r[4] if r[4] != '-' else 'NONE'
        if p not in pol_order:
            pol_order.append(p)
    pol_lines = ["    %s = %d," % (p, i) for i, p in enumerate(pol_order)]

    def tok(name):
        return '"%s"' % name

    def cname(policy):
        return 'Policy::%s' % (policy if policy != '-' else 'NONE')

    def rname(ret):
        return 'RetKind::%s' % ('STRING' if ret == 'str' else 'PLAIN')

    def sname(size):
        if size == '-':
            return 'SizeKind::NONE'
        return 'SizeKind::%s' % size.upper()

    row_lines = []
    for (name, lib, args, ret, policy, size) in rows:
        row_lines.append(
            "    {LibFamily::%s, %s, %s, %s, %s, %s},"
            % (lib, tok(name), tok(args), rname(ret), cname(policy), sname(size)))

    header = (HEADER.replace("{LIBS}", "\n".join(lib_lines))
                   .replace("{POLICIES}", "\n".join(pol_lines))
                   .replace("{ROWS}", "\n".join(row_lines)))

    if check:
        try:
            cur = open(out_path).read()
        except IOError:
            cur = ""
        if cur != header:
            print("thunkgen: %s is OUT OF DATE — run `make opgen-thunk` "
                  "(spec changed, generated header not synced)"
                  % out_path, file=sys.stderr)
            return 1
        print("thunkgen: %s is up to date (%d symbols)"
              % (out_path, len(rows)))
        return 0

    with open(out_path, "w") as fh:
        fh.write(header)
    print("wrote %s (%d symbols)" % (out_path, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
