#!/usr/bin/env python3
"""vkmarshalgen.py — generate Vulkan deep-marshal descriptors from vk.xml.

For an allowlist of commands whose dynamically-sized/nested parameters are
currently dispatched as plain 'p' (a host-driver crash waiting for a
multi-element array), emit:

  - per-struct descriptor tables (size + pointer-field map), where every
    pointer field records how to find its element count (same-struct u32
    count member offset, or fixed);
  - per-command "plans": which argument indices hold arrays of which
    struct descriptor, and which register holds the element count.

The runtime consumer lives in display_thunk.cpp (policy VK_CMD_DEEP):
a two-pass staging marshal (dry size pass, then fill) into a VkStage
arena, replacing guest pointers with host pointers before the host call.
All covered vkCmd*/device commands are INPUT-ONLY, so there is no
writeback.

Layouts come from vkxml.layout_all(), already validated byte-for-byte
against the vendored vulkan_core.h (see vk_layout validation).

Usage: python3 tools/opgen/vkmarshalgen.py <vk.xml> <out.hpp>
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vkxml import parse_registry, layout_all

# Commands converted to VK_CMD_DEEP. The count parameter for each dynamic
# array is derived AUTOMATICALLY from the registry's len="..." attribute
# (matched against sibling parameter names) — no hand-maintained indices.
# RAW = byte-counted void* handled specially.
CMD_PLANS = [
    'vkCmdSetViewport', 'vkCmdSetScissor', 'vkCmdPipelineBarrier',
    'vkCmdClearAttachments', 'vkCmdClearColorImage',
    'vkCmdClearDepthStencilImage', 'vkCmdCopyBuffer', 'vkCmdCopyImage',
    'vkCmdCopyBufferToImage', 'vkCmdCopyImageToBuffer',
    'vkCmdExecuteCommands', 'vkCmdWaitEvents', 'vkResetFences',
]

HEADER = r"""// opgen_vkmarshal.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/vkmarshalgen.py from the Khronos vk.xml
// registry (tools/vulkan-headers/registry/vk.xml). Struct sizes/layouts
// are validated against vulkan_core.h by the generator self-test.
//
// Consumed by DisplayThunk's VK_CMD_DEEP policy: a two-pass staging
// deep-marshal for command-batch parameters (barrier arrays, copy
// regions, clears, handle arrays...) that plain pointer translation
// cannot express.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace thunk {

enum : uint8_t {
    VKM_NONE = 0,
    VKM_STRUCT = 1,     // pointee is another descriptor
    VKM_HANDLE = 2,     // opaque handle(s) — copy verbatim
    VKM_RAW = 3,        // untyped bytes (void*)
};

struct VkFieldDesc {
    uint16_t off;          // byte offset of the pointer member
    uint8_t  elem;         // VKM_*
    uint8_t  elem_size;    // bytes per scalar/handle element
    int16_t  elem_struct;  // descriptor index when elem == VKM_STRUCT
    uint16_t count_off;    // offset of u32 count member in THIS struct
                           // (0xFFFF = use fixed_count)
    uint32_t fixed_count;  // element count when count_off == 0xFFFF
};

struct VkStructDesc {
    const char* name;
    uint16_t size;
    const VkFieldDesc* fields;
    uint16_t nfields;
};

struct VkPlanRef {
    uint8_t arg;           // register/args index of the array pointer
    uint8_t count_arg;     // register/args index holding the count
    uint8_t count_in_bytes;// 1 = count is a BYTE count (raw buffers)
    const VkStructDesc* desc;   // nullptr for VKM_RAW-style void*
};

struct VkCmdPlan {
    const char* name;
    uint8_t nrefs;
    const VkPlanRef* refs;
};

{STRUCT_TABLES}

// sentinel: opaque 8-byte element (handle arrays) copied verbatim
inline constexpr VkStructDesc kVkHandleElem = {
    "<handle>", 8, nullptr, 0};

inline constexpr VkStructDesc kVkStructs[] = {
{STRUCT_ROWS}
};

inline constexpr size_t kVkStructCount =
    sizeof(kVkStructs) / sizeof(kVkStructs[0]);

inline const VkStructDesc* vk_find_struct(const char* name) {
    for (size_t i = 0; i < kVkStructCount; i++)
        if (__builtin_strcmp(kVkStructs[i].name, name) == 0)
            return &kVkStructs[i];
    return nullptr;
}

{PLAN_TABLES}

inline constexpr VkCmdPlan kVkCmdPlans[] = {
{PLAN_ROWS}
};

inline constexpr size_t kVkCmdPlanCount =
    sizeof(kVkCmdPlans) / sizeof(kVkCmdPlans[0]);

inline const VkCmdPlan* vk_find_cmd_plan(const char* name) {
    for (size_t i = 0; i < kVkCmdPlanCount; i++)
        if (__builtin_strcmp(kVkCmdPlans[i].name, name) == 0)
            return &kVkCmdPlans[i];
    return nullptr;
}

} // namespace thunk
} // namespace arm64emu
"""


def main():
    xml_path = sys.argv[1] if len(sys.argv) > 1 else \
        'tools/vulkan-headers/registry/vk.xml'
    out_path = sys.argv[2] if len(sys.argv) > 2 else \
        'include/opgen_vkmarshal.hpp'
    reg = parse_registry(xml_path)
    layouts = layout_all(reg)

    # ── collect needed structs (closure over plans) ──────────────────
    needed = {}       # struct name -> list of (offset, FieldPtr-like info)
    order = []
    def member_offset(lay, mname):
        # recompute offsets to find the count member's byte position
        import re
        off = 0

        def au(v, a):
            return (v + a - 1) & ~(a - 1)
        for m in reg['structs'][lay.name]:
            cnt = m.array_len
            if m.is_ptr:
                off = au(off, 8)
                o = off
                off += 8 * (cnt or 1)
                if m.name == mname:
                    return o
                continue
            if m.type in layouts:
                sub = layouts[m.type]
                esz, eal = sub.size, sub.align
            else:
                from vkxml import SCALAR_SIZES
                esz = SCALAR_SIZES.get(m.type)
                if esz is None and m.type in reg['handles']:
                    esz = 8
                if esz is None and m.type in reg['enum_names']:
                    esz = 4
                if esz is None and m.type in reg['bitmask_names']:
                    esz = 8 if m.type in reg['bitmask64'] else 4
                eal = min(esz or 1, 8)
            if esz is None:
                return None
            off = au(off, eal)
            o = off
            off += esz * (cnt or 1)
            if m.name == mname:
                return o
        return None

    def want_struct(name):
        if name in needed:
            return True
        lay = layouts.get(name)
        if lay is None:
            return False
        needed[name] = True
        order.append(name)
        return True

    plans = {}
    for cmd in CMD_PLANS:
        c = reg['commands'].get(cmd)
        if c is None:
            print(f'WARN: {cmd} not in registry', file=sys.stderr)
            continue
        plist = []
        ok = True
        for pidx, p in enumerate(c.params):
            if not p.is_ptr:
                continue
            ln = p.len_ or ''
            # resolve len expression to a sibling param index
            cidx = None
            base = ln.split(',')[0].strip()
            for j, q in enumerate(c.params):
                if q.name == base and q.is_ptr == 0:
                    cidx = j
                    break
            if cidx is None:
                # no/unknown len: not a counted array — leave it on the
                # generic single-element bounce path
                continue
            if p.type == 'void':
                plist.append((pidx, cidx, None))
                continue
            if p.type in reg['handles']:
                plist.append((pidx, cidx, '<handle>'))
                continue
            if p.type not in layouts:
                print(f'WARN: {cmd} param {p.name}: no layout for '
                      f'{p.type}', file=sys.stderr)
                ok = False
                break
            want_struct(p.type)
            plist.append((pidx, cidx, p.type))
        if ok:
            plans[cmd] = plist

    # closure: recurse into struct-typed pointer fields
    i = 0
    while i < len(order):
        name = order[i]
        i += 1
        lay = layouts[name]
        for pf in lay.ptrs:
            if pf.elem.startswith('struct:'):
                want_struct(pf.elem.split(':', 1)[1])

    # ── field descriptors ────────────────────────────────────────────
    struct_index = {n: i for i, n in enumerate(order)}
    tables = []
    rows = []
    for name in order:
        lay = layouts[name]
        fields = []
        for pf in lay.ptrs:
            elem = {'struct': 1, 'handle': 2, 'ptr': 3,
                    'char': 3}.get(pf.elem.split(':')[0], 3)
            elem_struct = 0
            elem_size = 8
            if pf.elem.startswith('struct:'):
                elem_struct = struct_index[pf.elem.split(':', 1)[1]]
                elem = 1
                elem_size = layouts[pf.elem.split(':', 1)[1]].size
            elif pf.elem == 'handle':
                elem, elem_size = 2, 8
            elif pf.elem == 'char':
                elem, elem_size = 3, 1   # treated as verbatim bytes
            if pf.count == 'fixed:1':
                count_off, fixed = 0xFFFF, 1
            elif pf.count == 'nullterm':
                count_off, fixed = 0xFFFF, 1   # single element; NUL-safe
            else:
                mname = pf.count.split(':', 1)[1]
                co = member_offset(lay, mname.split('.')[0])
                if co is None:
                    print(f'WARN: {name}: cannot locate count member '
                          f'{mname}', file=sys.stderr)
                    continue
                count_off, fixed = co, 0
            fields.append((pf.offset, elem, elem_size, elem_struct,
                           count_off, fixed))
        if fields:
            arr_name = f'kFields_{name}'
            tables.append(
                f'inline constexpr VkFieldDesc {arr_name}[] = {{\n' +
                ''.join(
                    f'    {{{off},{el},{esz},{est},'
                    f'{("0x%04X" % co) if co != 0xFFFF else str(co)},{fx}}},\n'
                    for (off, el, esz, est, co, fx) in fields) +
                '};')
            rows.append(f'    {{"{name}", {lay.size}, {arr_name}, '
                        f'{len(fields)}}},')
        else:
            rows.append(f'    {{"{name}", {lay.size}, nullptr, 0}},')

    plan_tables, plan_rows = [], []
    for cmd, plist in plans.items():
        refs = []
        for (pidx, cidx, sname) in plist:
            if sname == '<handle>':
                refs.append(f'    {{{pidx},{cidx},0,&kVkHandleElem}},')
                continue
            desc = f'&kVkStructs[{struct_index[sname]}]' if sname else 'nullptr'
            refs.append(f'    {{{pidx},{cidx},'
                        f'{0 if sname else 1},{desc}}},')
        arr = f'kRefs_{cmd}'
        plan_tables.append(
            f'inline constexpr VkPlanRef {arr}[] = {{\n' +
            '\n'.join(refs) + '\n};')
        plan_rows.append(f'    {{"{cmd}", {len(plist)}, {arr}}},')

    out = HEADER
    out = out.replace('{STRUCT_TABLES}', '\n\n'.join(tables))
    out = out.replace('{STRUCT_ROWS}', '\n'.join(rows))
    out = out.replace('{PLAN_TABLES}', '\n\n'.join(plan_tables))
    out = out.replace('{PLAN_ROWS}', '\n'.join(plan_rows))
    with open(out_path, 'w') as fh:
        fh.write(out)
    print(f'wrote {out_path}: {len(order)} struct descriptors, '
          f'{len(plans)} command plans')


if __name__ == '__main__':
    main()
