#!/usr/bin/env python3
"""wlgen.py — Wayland protocol signature tables for DisplayThunk.

Parses the real protocol definitions (tools/wayland-xml/wayland.xml +
tools/wayland-xml/xdg-shell.xml, vendored from wayland-scanner's source
— same model as the vendored Khronos vk.xml/gl.xml) and emits a compact
per-message signature table: interface, opcode, and one letter per
argument (i=int u=uint f=fixed s=string o=object n=new_id a=array
h=fd, uppercase = nullable).

Why: ~87 PROXY-policy symbols have no proxy implementation. Most of
the missing wl_ core (display dispatch, marshal, roundtrip) needs the
per-message signatures to marshal guest/host calls. Hand-writing those
from memory is how you get silent corruption; generating them from the
protocol XML keeps the proxy honest the same way vkxmlcheck keeps the
thunk table honest.

Usage:
  python3 tools/opgen/wlgen.py [wayland.xml] [xdg-shell.xml] <out.hpp>
  python3 tools/opgen/wlgen.py --check [wayland.xml] [xdg-shell.xml] <out.hpp>
  python3 tools/opgen/wlgen.py --classify [wayland.xml]   # backlog report
"""
import sys
import xml.etree.ElementTree as ET

TYPE_LETTER = {
    "int": "i", "uint": "u", "fixed": "f", "string": "s",
    "object": "o", "new_id": "n", "array": "a", "fd": "h",
}

HEADER = r"""// opgen_wl.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/wlgen.py from wayland.xml + xdg-shell.xml
// (the same sources wayland-scanner uses). Per-message signatures for
// the DisplayProxy: one letter per argument, uppercase = nullable.
//
// Regenerate with: make wlgen
#pragma once
#include <cstddef>
#include <cstdint>

namespace arm64emu {
namespace wl {

struct Message {
    const char* iface;   // interface name, e.g. "wl_surface"
    const char* name;    // method name, e.g. "attach"
    uint32_t    opcode;  // index within its kind (requests/events separate)
    const char* sig;     // arg types, "" when argless
    bool        is_event;
    // New-object interface for constructor-style requests (bind,
    // create_surface, ...): the type the created id maps to. "" when
    // the request creates nothing.
    const char* created;
};

inline constexpr Message kMessages[] = {
{ROWS}
};

inline constexpr size_t kMessageCount =
    sizeof(kMessages) / sizeof(kMessages[0]);

// Number of events an interface defines (listener struct length).
// constexpr so listener setup stays table-driven, not hand-counted.
inline constexpr size_t event_count(const char* iface) {
    size_t n = 0;
    for (size_t i = 0; i < kMessageCount; i++) {
        const Message& m = kMessages[i];
        if (!m.is_event) continue;
        const char* a = m.iface;
        const char* b = iface;
        while (*a && *a == *b) { a++; b++; }
        if (*a == *b) n++;
    }
    return n;
}

// Find a message signature by interface + opcode. Returns nullptr when
// the pair is unknown (caller falls back to the loud-miss path).
// constexpr so static_assert can pin canary rows at build time.
inline constexpr const Message* find(bool is_event, const char* iface,
                                     uint32_t opcode) {
    for (size_t i = 0; i < kMessageCount; i++) {
        const Message& m = kMessages[i];
        if (m.is_event != is_event || m.opcode != opcode) continue;
        const char* a = m.iface;
        const char* b = iface;
        while (*a && *a == *b) { a++; b++; }
        if (*a == *b) return &m;
    }
    return nullptr;
}

}  // namespace wl
}  // namespace arm64emu
"""


def parse(xml_path):
    tree = ET.parse(xml_path)
    messages = []
    for iface in tree.getroot().findall("interface"):
        iname = iface.get("name")
        for kind, is_event in (("request", False), ("event", True)):
            for idx, msg in enumerate(iface.findall(kind)):
                sig = []
                created = ""
                for arg in msg.findall("arg"):
                    letter = TYPE_LETTER.get(arg.get("type") or "", "?")
                    if arg.get("allow-null") in ("true", "1"):
                        letter = letter.upper()
                    sig.append(letter)
                    if arg.get("type") == "new_id" and arg.get("interface"):
                        created = arg.get("interface")
                messages.append((iname, msg.get("name"), idx,
                                 "".join(sig), is_event, created))
    return messages


def emit(messages):
    rows = []
    for iname, mname, opcode, sig, is_event, created in messages:
        rows.append(
            f'    {{"{iname}", "{mname}", {opcode}u, "{sig}", '
            f'{"true" if is_event else "false"}, "{created}"}},')
    return HEADER.replace("{ROWS}", "\n".join(rows))


def classify(messages):
    """Split requests into trivial vs hand-work buckets and print."""
    trivial, complex = [], []
    for iname, mname, opcode, sig, is_event in messages:
        if is_event:
            continue
        # new_id / string / array / fd need real marshalling work.
        if any(c in sig.lower() for c in ("n", "s", "a", "h")):
            complex.append((iname, mname, opcode, sig))
        else:
            trivial.append((iname, mname, opcode, sig))
    print(f"requests: {len(trivial) + len(complex)}, "
          f"trivial-forwardable: {len(trivial)}, "
          f"needs-handwork: {len(complex)}")
    print("--- needs handwork ---")
    for iname, mname, opcode, sig in complex:
        print(f"  {iname}.{mname} [{opcode}] sig={sig or '-'}")
    return 0


DEFAULT_XML = "tools/wayland-xml/wayland.xml"


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    check = "--check" in argv
    do_classify = "--classify" in argv
    # last positional is the output header, the rest are inputs.
    # (--classify takes only inputs, no output.)
    if do_classify:
        xml_paths = args if args else [DEFAULT_XML]
        messages = []
        for xml_path in xml_paths:
            messages.extend(parse(xml_path))
        return classify(messages)
    out_path = args[-1] if args else None
    xml_paths = args[:-1] if len(args) > 1 else [DEFAULT_XML]
    if out_path is None:
        sys.stderr.write("usage: wlgen.py [--check] [xml...] <out.hpp>\n")
        return 2
    messages = []
    for xml_path in xml_paths:
        messages.extend(parse(xml_path))
    text = emit(messages)
    if check:
        try:
            with open(out_path) as fh:
                current = fh.read()
        except FileNotFoundError:
            current = None
        if current != text:
            sys.stderr.write(
                f"wlgen: {out_path} is stale — run `make wlgen`\n")
            return 1
        print(f"wlgen: {out_path} is up to date "
              f"({len(messages)} messages)")
        return 0
    with open(out_path, "w") as fh:
        fh.write(text)
    print(f"wrote {out_path} ({len(messages)} messages)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
