// opgen_fpfixed.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/fpgen.py from tools/opgen/fp_fixconv.txt.
// To add/modify an FP fixed-point conversion opcode edit the spec and
// run: make opgen-fpfixed
//
// Single source of truth for the scaled int<->FP conversions
// (SCVTF/UCVTF/FCVTZS/FCVTZU with #fbits). The interpreter
// (interp_fp.cpp), the IR translator (ir_translate_fp.cpp) and the JIT
// block heuristic (jit_translate.cpp) all classify with
// arm64emu::fpfixed::classify(), so the three copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace fpfixed {

enum class Family : uint8_t {
    FIXCONV = 0,
    UNKNOWN = 1,
};

struct Op {
    Family family;
    uint16_t opc;            // stable per-opcode id (row index in spec)
    uint8_t subop;           // per-family semantic sub-opcode (IRSUB)
    const char* name;
};

inline Op classify(uint32_t op) {
    const uint32_t Q    = (op >> 30) & 1u;
    const uint32_t U    = (op >> 29) & 1u;
    const uint32_t size = (op >> 22) & 3u;
    (void)U;
    (void)Q;
    (void)size;
    if ((op & 0x7F3E0000U) == 0x1E020000U) return Op{Family::FIXCONV, 0, 0, "SCVTF_GPR"};
    if ((op & 0x7F3E0000U) == 0x1E180000U) return Op{Family::FIXCONV, 1, 1, "FCVTZS_GPR"};
    if ((op & 0xDF80E400U) == 0x5F00E400U && (((op >> 11) & 3) == 0)) return Op{Family::FIXCONV, 2, 2, "SCVTF_FP"};
    if ((op & 0xDF80E400U) == 0x5F00E400U && (((op >> 11) & 3) == 3)) return Op{Family::FIXCONV, 3, 3, "FCVTZS_FP"};
    return Op{Family::UNKNOWN, 0, 0, "unknown"};
}

} // namespace fpfixed
} // namespace arm64emu
