// opgen_vkmarshal.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/vkmarshalgen.py from the Khronos vk.xml
// registry (tools/vulkan-headers/registry/vk.xml). Struct sizes/layouts
// are validated against vulkan_core.h by the generator self-test.
//
// Consumed by DisplayThunk's VK_CMD_DEEP policy: a two-pass staging
// deep-marshal for command-batch parameters (barrier arrays, copy
// regions, clears, handle arrays...) that plain pointer translation
// cannot express.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace thunk {

enum : uint8_t {
    VKM_NONE = 0,
    VKM_STRUCT = 1,     // pointee is another descriptor
    VKM_HANDLE = 2,     // opaque handle(s) — copy verbatim
    VKM_RAW = 3,        // untyped bytes (void*)
};

struct VkFieldDesc {
    uint16_t off;          // byte offset of the pointer member
    uint8_t  elem;         // VKM_*
    uint8_t  elem_size;    // bytes per scalar/handle element
    int16_t  elem_struct;  // descriptor index when elem == VKM_STRUCT
    uint16_t count_off;    // offset of u32 count member in THIS struct
                           // (0xFFFF = use fixed_count)
    uint32_t fixed_count;  // element count when count_off == 0xFFFF
};

struct VkStructDesc {
    const char* name;
    uint16_t size;
    const VkFieldDesc* fields;
    uint16_t nfields;
};

struct VkPlanRef {
    uint8_t arg;           // register/args index of the array pointer
    uint8_t count_arg;     // register/args index holding the count
    uint8_t count_in_bytes;// 1 = count is a BYTE count (raw buffers)
    const VkStructDesc* desc;   // nullptr for VKM_RAW-style void*
};

struct VkCmdPlan {
    const char* name;
    uint8_t nrefs;
    const VkPlanRef* refs;
};

inline constexpr VkFieldDesc kFields_VkMemoryBarrier[] = {
    {8,3,8,0,65535,1},
};

inline constexpr VkFieldDesc kFields_VkBufferMemoryBarrier[] = {
    {8,3,8,0,65535,1},
};

inline constexpr VkFieldDesc kFields_VkImageMemoryBarrier[] = {
    {8,3,8,0,65535,1},
};

// sentinel: opaque 8-byte element (handle arrays) copied verbatim
inline constexpr VkStructDesc kVkHandleElem = {
    "<handle>", 8, nullptr, 0};

inline constexpr VkStructDesc kVkStructs[] = {
    {"VkViewport", 24, nullptr, 0},
    {"VkRect2D", 16, nullptr, 0},
    {"VkMemoryBarrier", 24, kFields_VkMemoryBarrier, 1},
    {"VkBufferMemoryBarrier", 56, kFields_VkBufferMemoryBarrier, 1},
    {"VkImageMemoryBarrier", 72, kFields_VkImageMemoryBarrier, 1},
    {"VkClearAttachment", 24, nullptr, 0},
    {"VkClearRect", 24, nullptr, 0},
    {"VkImageSubresourceRange", 20, nullptr, 0},
    {"VkBufferCopy", 24, nullptr, 0},
    {"VkImageCopy", 68, nullptr, 0},
    {"VkBufferImageCopy", 56, nullptr, 0},
};

inline constexpr size_t kVkStructCount =
    sizeof(kVkStructs) / sizeof(kVkStructs[0]);

inline const VkStructDesc* vk_find_struct(const char* name) {
    for (size_t i = 0; i < kVkStructCount; i++)
        if (__builtin_strcmp(kVkStructs[i].name, name) == 0)
            return &kVkStructs[i];
    return nullptr;
}

inline constexpr VkPlanRef kRefs_vkCmdSetViewport[] = {
    {3,2,0,&kVkStructs[0]},
};

inline constexpr VkPlanRef kRefs_vkCmdSetScissor[] = {
    {3,2,0,&kVkStructs[1]},
};

inline constexpr VkPlanRef kRefs_vkCmdPipelineBarrier[] = {
    {5,4,0,&kVkStructs[2]},
    {7,6,0,&kVkStructs[3]},
    {9,8,0,&kVkStructs[4]},
};

inline constexpr VkPlanRef kRefs_vkCmdClearAttachments[] = {
    {2,1,0,&kVkStructs[5]},
    {4,3,0,&kVkStructs[6]},
};

inline constexpr VkPlanRef kRefs_vkCmdClearColorImage[] = {
    {5,4,0,&kVkStructs[7]},
};

inline constexpr VkPlanRef kRefs_vkCmdClearDepthStencilImage[] = {
    {5,4,0,&kVkStructs[7]},
};

inline constexpr VkPlanRef kRefs_vkCmdCopyBuffer[] = {
    {4,3,0,&kVkStructs[8]},
};

inline constexpr VkPlanRef kRefs_vkCmdCopyImage[] = {
    {6,5,0,&kVkStructs[9]},
};

inline constexpr VkPlanRef kRefs_vkCmdCopyBufferToImage[] = {
    {5,4,0,&kVkStructs[10]},
};

inline constexpr VkPlanRef kRefs_vkCmdCopyImageToBuffer[] = {
    {5,4,0,&kVkStructs[10]},
};

inline constexpr VkPlanRef kRefs_vkCmdExecuteCommands[] = {
    {2,1,0,&kVkHandleElem},
};

inline constexpr VkPlanRef kRefs_vkCmdWaitEvents[] = {
    {2,1,0,&kVkHandleElem},
    {6,5,0,&kVkStructs[2]},
    {8,7,0,&kVkStructs[3]},
    {10,9,0,&kVkStructs[4]},
};

inline constexpr VkPlanRef kRefs_vkResetFences[] = {
    {2,1,0,&kVkHandleElem},
};

inline constexpr VkCmdPlan kVkCmdPlans[] = {
    {"vkCmdSetViewport", 1, kRefs_vkCmdSetViewport},
    {"vkCmdSetScissor", 1, kRefs_vkCmdSetScissor},
    {"vkCmdPipelineBarrier", 3, kRefs_vkCmdPipelineBarrier},
    {"vkCmdClearAttachments", 2, kRefs_vkCmdClearAttachments},
    {"vkCmdClearColorImage", 1, kRefs_vkCmdClearColorImage},
    {"vkCmdClearDepthStencilImage", 1, kRefs_vkCmdClearDepthStencilImage},
    {"vkCmdCopyBuffer", 1, kRefs_vkCmdCopyBuffer},
    {"vkCmdCopyImage", 1, kRefs_vkCmdCopyImage},
    {"vkCmdCopyBufferToImage", 1, kRefs_vkCmdCopyBufferToImage},
    {"vkCmdCopyImageToBuffer", 1, kRefs_vkCmdCopyImageToBuffer},
    {"vkCmdExecuteCommands", 1, kRefs_vkCmdExecuteCommands},
    {"vkCmdWaitEvents", 4, kRefs_vkCmdWaitEvents},
    {"vkResetFences", 1, kRefs_vkResetFences},
};

inline constexpr size_t kVkCmdPlanCount =
    sizeof(kVkCmdPlans) / sizeof(kVkCmdPlans[0]);

inline const VkCmdPlan* vk_find_cmd_plan(const char* name) {
    for (size_t i = 0; i < kVkCmdPlanCount; i++)
        if (__builtin_strcmp(kVkCmdPlans[i].name, name) == 0)
            return &kVkCmdPlans[i];
    return nullptr;
}

} // namespace thunk
} // namespace arm64emu
