// opgen_wl.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/wlgen.py from wayland.xml (the same source
// wayland-scanner uses). Per-message signatures for the DisplayProxy:
// one letter per argument, uppercase = nullable.
//
// Regenerate with: make wlgen
#pragma once
#include <cstddef>
#include <cstdint>

namespace arm64emu {
namespace wl {

struct Message {
    const char* iface;   // interface name, e.g. "wl_surface"
    const char* name;    // method name, e.g. "attach"
    uint32_t    opcode;  // index within its kind (requests/events separate)
    const char* sig;     // arg types, "" when argless
    bool        is_event;
};

inline constexpr Message kMessages[] = {
    {"wl_display", "sync", 0u, "n", false},
    {"wl_display", "get_registry", 1u, "n", false},
    {"wl_display", "error", 0u, "ous", true},
    {"wl_display", "delete_id", 1u, "u", true},
    {"wl_registry", "bind", 0u, "un", false},
    {"wl_registry", "global", 0u, "usu", true},
    {"wl_registry", "global_remove", 1u, "u", true},
    {"wl_callback", "done", 0u, "u", true},
    {"wl_compositor", "create_surface", 0u, "n", false},
    {"wl_compositor", "create_region", 1u, "n", false},
    {"wl_compositor", "release", 2u, "", false},
    {"wl_shm_pool", "create_buffer", 0u, "niiiiu", false},
    {"wl_shm_pool", "destroy", 1u, "", false},
    {"wl_shm_pool", "resize", 2u, "i", false},
    {"wl_shm", "create_pool", 0u, "nhi", false},
    {"wl_shm", "release", 1u, "", false},
    {"wl_shm", "format", 0u, "u", true},
    {"wl_buffer", "destroy", 0u, "", false},
    {"wl_buffer", "release", 0u, "", true},
    {"wl_data_offer", "accept", 0u, "uS", false},
    {"wl_data_offer", "receive", 1u, "sh", false},
    {"wl_data_offer", "destroy", 2u, "", false},
    {"wl_data_offer", "finish", 3u, "", false},
    {"wl_data_offer", "set_actions", 4u, "uu", false},
    {"wl_data_offer", "offer", 0u, "s", true},
    {"wl_data_offer", "source_actions", 1u, "u", true},
    {"wl_data_offer", "action", 2u, "u", true},
    {"wl_data_source", "offer", 0u, "s", false},
    {"wl_data_source", "destroy", 1u, "", false},
    {"wl_data_source", "set_actions", 2u, "u", false},
    {"wl_data_source", "target", 0u, "S", true},
    {"wl_data_source", "send", 1u, "sh", true},
    {"wl_data_source", "cancelled", 2u, "", true},
    {"wl_data_source", "dnd_drop_performed", 3u, "", true},
    {"wl_data_source", "dnd_finished", 4u, "", true},
    {"wl_data_source", "action", 5u, "u", true},
    {"wl_data_device", "start_drag", 0u, "OoOu", false},
    {"wl_data_device", "set_selection", 1u, "Ou", false},
    {"wl_data_device", "release", 2u, "", false},
    {"wl_data_device", "data_offer", 0u, "n", true},
    {"wl_data_device", "enter", 1u, "uoffO", true},
    {"wl_data_device", "leave", 2u, "", true},
    {"wl_data_device", "motion", 3u, "uff", true},
    {"wl_data_device", "drop", 4u, "", true},
    {"wl_data_device", "selection", 5u, "O", true},
    {"wl_data_device_manager", "create_data_source", 0u, "n", false},
    {"wl_data_device_manager", "get_data_device", 1u, "no", false},
    {"wl_data_device_manager", "release", 2u, "", false},
    {"wl_shell", "get_shell_surface", 0u, "no", false},
    {"wl_shell_surface", "pong", 0u, "u", false},
    {"wl_shell_surface", "move", 1u, "ou", false},
    {"wl_shell_surface", "resize", 2u, "ouu", false},
    {"wl_shell_surface", "set_toplevel", 3u, "", false},
    {"wl_shell_surface", "set_transient", 4u, "oiiu", false},
    {"wl_shell_surface", "set_fullscreen", 5u, "uuO", false},
    {"wl_shell_surface", "set_popup", 6u, "ouoiiu", false},
    {"wl_shell_surface", "set_maximized", 7u, "O", false},
    {"wl_shell_surface", "set_title", 8u, "s", false},
    {"wl_shell_surface", "set_class", 9u, "s", false},
    {"wl_shell_surface", "ping", 0u, "u", true},
    {"wl_shell_surface", "configure", 1u, "uii", true},
    {"wl_shell_surface", "popup_done", 2u, "", true},
    {"wl_surface", "destroy", 0u, "", false},
    {"wl_surface", "attach", 1u, "Oii", false},
    {"wl_surface", "damage", 2u, "iiii", false},
    {"wl_surface", "frame", 3u, "n", false},
    {"wl_surface", "set_opaque_region", 4u, "O", false},
    {"wl_surface", "set_input_region", 5u, "O", false},
    {"wl_surface", "commit", 6u, "", false},
    {"wl_surface", "set_buffer_transform", 7u, "i", false},
    {"wl_surface", "set_buffer_scale", 8u, "i", false},
    {"wl_surface", "damage_buffer", 9u, "iiii", false},
    {"wl_surface", "offset", 10u, "ii", false},
    {"wl_surface", "get_release", 11u, "n", false},
    {"wl_surface", "enter", 0u, "o", true},
    {"wl_surface", "leave", 1u, "o", true},
    {"wl_surface", "preferred_buffer_scale", 2u, "i", true},
    {"wl_surface", "preferred_buffer_transform", 3u, "u", true},
    {"wl_seat", "get_pointer", 0u, "n", false},
    {"wl_seat", "get_keyboard", 1u, "n", false},
    {"wl_seat", "get_touch", 2u, "n", false},
    {"wl_seat", "release", 3u, "", false},
    {"wl_seat", "capabilities", 0u, "u", true},
    {"wl_seat", "name", 1u, "s", true},
    {"wl_pointer", "set_cursor", 0u, "uOii", false},
    {"wl_pointer", "release", 1u, "", false},
    {"wl_pointer", "enter", 0u, "uoff", true},
    {"wl_pointer", "leave", 1u, "uo", true},
    {"wl_pointer", "motion", 2u, "uff", true},
    {"wl_pointer", "button", 3u, "uuuu", true},
    {"wl_pointer", "axis", 4u, "uuf", true},
    {"wl_pointer", "frame", 5u, "", true},
    {"wl_pointer", "axis_source", 6u, "u", true},
    {"wl_pointer", "axis_stop", 7u, "uu", true},
    {"wl_pointer", "axis_discrete", 8u, "ui", true},
    {"wl_pointer", "axis_value120", 9u, "ui", true},
    {"wl_pointer", "axis_relative_direction", 10u, "uu", true},
    {"wl_keyboard", "release", 0u, "", false},
    {"wl_keyboard", "keymap", 0u, "uhu", true},
    {"wl_keyboard", "enter", 1u, "uoa", true},
    {"wl_keyboard", "leave", 2u, "uo", true},
    {"wl_keyboard", "key", 3u, "uuuu", true},
    {"wl_keyboard", "modifiers", 4u, "uuuuu", true},
    {"wl_keyboard", "repeat_info", 5u, "ii", true},
    {"wl_touch", "release", 0u, "", false},
    {"wl_touch", "down", 0u, "uuoiff", true},
    {"wl_touch", "up", 1u, "uui", true},
    {"wl_touch", "motion", 2u, "uiff", true},
    {"wl_touch", "frame", 3u, "", true},
    {"wl_touch", "cancel", 4u, "", true},
    {"wl_touch", "shape", 5u, "iff", true},
    {"wl_touch", "orientation", 6u, "if", true},
    {"wl_output", "release", 0u, "", false},
    {"wl_output", "geometry", 0u, "iiiiissi", true},
    {"wl_output", "mode", 1u, "uiii", true},
    {"wl_output", "done", 2u, "", true},
    {"wl_output", "scale", 3u, "i", true},
    {"wl_output", "name", 4u, "s", true},
    {"wl_output", "description", 5u, "s", true},
    {"wl_region", "destroy", 0u, "", false},
    {"wl_region", "add", 1u, "iiii", false},
    {"wl_region", "subtract", 2u, "iiii", false},
    {"wl_subcompositor", "destroy", 0u, "", false},
    {"wl_subcompositor", "get_subsurface", 1u, "noo", false},
    {"wl_subsurface", "destroy", 0u, "", false},
    {"wl_subsurface", "set_position", 1u, "ii", false},
    {"wl_subsurface", "place_above", 2u, "o", false},
    {"wl_subsurface", "place_below", 3u, "o", false},
    {"wl_subsurface", "set_sync", 4u, "", false},
    {"wl_subsurface", "set_desync", 5u, "", false},
    {"wl_fixes", "destroy", 0u, "", false},
    {"wl_fixes", "destroy_registry", 1u, "o", false},
};

inline constexpr size_t kMessageCount =
    sizeof(kMessages) / sizeof(kMessages[0]);

// Find a message signature by interface + opcode. Returns nullptr when
// the pair is unknown (caller falls back to the loud-miss path).
// constexpr so static_assert can pin canary rows at build time.
inline constexpr const Message* find(bool is_event, const char* iface,
                                     uint32_t opcode) {
    for (size_t i = 0; i < kMessageCount; i++) {
        const Message& m = kMessages[i];
        if (m.is_event != is_event || m.opcode != opcode) continue;
        const char* a = m.iface;
        const char* b = iface;
        while (*a && *a == *b) { a++; b++; }
        if (*a == *b) return &m;
    }
    return nullptr;
}

}  // namespace wl
}  // namespace arm64emu
