// opgen_simd.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/opgen.py from tools/opgen/simd_dp.txt.
// To add/modify a SIMD opcode edit the spec and run: make opgen
//
// Single source of truth for SIMD_DP decode. The interpreter
// (interp_fp.cpp), the IR translator (ir_translate_fp.cpp) and the JIT
// block heuristic (jit_translate.cpp) all classify with
// arm64emu::simd::classify(), so the three copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace simd {

enum class Family : uint8_t {
    INT_ARITH = 0,
    INT_CMP = 1,
    LOGIC = 2,
    FP = 3,
    MODIMM = 4,
    SHIFT = 5,
    DUP = 6,
    UMOV = 7,
    CRYPTO = 8,
    PMISC = 9,
    CVTF = 10,
    ADDP = 11,
    XTN = 12,
    TBL = 13,
    INS = 14,
    PERMUTE = 15,
    PAIRMIN = 16,
    ABDL = 17,
    ABD = 18,
    ADDW = 19,
    ADDHN = 20,
    SHRN_SAT = 21,
    MUL_ELEM = 22,
    SMOV = 23,
    SATADDSUB = 24,
    FP_UNARY = 25,
    FP_INDEXED = 26,
    UNKNOWN = 27,
};

struct Op {
    Family family;
    uint16_t opc;            // stable per-opcode id (row index in spec)
    uint8_t subop;           // per-family semantic sub-opcode (IRSUB)
    const char* name;
};

inline Op classify(uint32_t op) {
    const uint32_t Q    = (op >> 30) & 1u;
    const uint32_t U    = (op >> 29) & 1u;
    const uint32_t size = (op >> 22) & 3u;
    (void)U;
    if ((op & 0xBF20FC00U) == 0x0E208400U) return Op{Family::INT_ARITH, 0, 0, "ADD"};
    if ((op & 0xBF20FC00U) == 0x2E208400U) return Op{Family::INT_ARITH, 1, 1, "SUB"};
    if ((op & 0xBF20FC00U) == 0x0E209C00U && (size != 3)) return Op{Family::INT_ARITH, 2, 2, "MUL"};
    if ((op & 0xBF20FC00U) == 0x2E206C00U) return Op{Family::INT_ARITH, 3, 3, "UMIN"};
    if ((op & 0xBF20FC00U) == 0x2E206400U) return Op{Family::INT_ARITH, 4, 4, "UMAX"};
    if ((op & 0xBF20FC00U) == 0x0E206C00U) return Op{Family::INT_ARITH, 5, 5, "SMIN"};
    if ((op & 0xBF20FC00U) == 0x0E206400U) return Op{Family::INT_ARITH, 6, 6, "SMAX"};
    if ((op & 0xBF20FC00U) == 0x0E203400U) return Op{Family::INT_CMP, 7, 1, "CMGT"};
    if ((op & 0xBF20FC00U) == 0x0E203C00U) return Op{Family::INT_CMP, 8, 2, "CMGE"};
    if ((op & 0xBF20FC00U) == 0x2E208C00U) return Op{Family::INT_CMP, 9, 0, "CMEQ"};
    if ((op & 0xBF20FC00U) == 0x2E203400U) return Op{Family::INT_CMP, 10, 3, "CMHI"};
    if ((op & 0xBF20FC00U) == 0x2E203C00U) return Op{Family::INT_CMP, 11, 4, "CMHS"};
    if ((op & 0xBFE0FC00U) == 0x0E201C00U) return Op{Family::LOGIC, 12, 0, "AND"};
    if ((op & 0xBFE0FC00U) == 0x0EA01C00U) return Op{Family::LOGIC, 13, 1, "ORR"};
    if ((op & 0xBFE0FC00U) == 0x2E201C00U) return Op{Family::LOGIC, 14, 2, "EOR"};
    if ((op & 0xBFE0FC00U) == 0x0E601C00U) return Op{Family::LOGIC, 15, 3, "BIC"};
    if ((op & 0xBFE0FC00U) == 0x0EE01C00U) return Op{Family::LOGIC, 16, 4, "ORN"};
    if ((op & 0xBFA0FC00U) == 0x0E20D400U) return Op{Family::FP, 17, 0, "FADD"};
    if ((op & 0xBFA0FC00U) == 0x0EA0D400U) return Op{Family::FP, 18, 1, "FSUB"};
    if ((op & 0xBFA0FC00U) == 0x2E20DC00U) return Op{Family::FP, 19, 2, "FMUL"};
    if ((op & 0xBFA0FC00U) == 0x2E20FC00U) return Op{Family::FP, 20, 3, "FDIV"};
    if ((op & 0xBFA0FC00U) == 0x0E20F400U) return Op{Family::FP, 21, 4, "FMAX"};
    if ((op & 0xBFA0FC00U) == 0x0EA0F400U) return Op{Family::FP, 22, 5, "FMIN"};
    if ((op & 0xBFA0FC00U) == 0x0E20C400U) return Op{Family::FP, 23, 6, "FMAXNM"};
    if ((op & 0xBFA0FC00U) == 0x0EA0C400U) return Op{Family::FP, 24, 7, "FMINNM"};
    if ((op & 0xBFA0FC00U) == 0x0E20DC00U) return Op{Family::FP, 25, 11, "FMULX"};
    if ((op & 0xBFA0FC00U) == 0x2EA0D400U) return Op{Family::FP, 26, 13, "FABD"};
    if ((op & 0xBFA0FC00U) == 0x0E20CC00U) return Op{Family::FP, 27, 14, "FMLA"};
    if ((op & 0xBFA0FC00U) == 0x0EA0CC00U) return Op{Family::FP, 28, 15, "FMLS"};
    if ((op & 0x9F800C00U) == 0x0F000400U && (((op >> 19) & 0xF) == 0)) return Op{Family::MODIMM, 29, 0, "MOVI"};
    if ((op & 0xBF00FC00U) == 0x0F005400U) return Op{Family::SHIFT, 30, 0, "SHL"};
    if ((op & 0xBF00FC00U) == 0x2F000400U) return Op{Family::SHIFT, 31, 1, "USHR"};
    if ((op & 0xBF00FC00U) == 0x0F000400U) return Op{Family::SHIFT, 32, 2, "SSHR"};
    if ((op & 0xBF00FC00U) == 0x2F001400U) return Op{Family::SHIFT, 33, 3, "USRA"};
    if ((op & 0xBF00FC00U) == 0x0F001400U) return Op{Family::SHIFT, 34, 4, "SSRA"};
    if ((op & 0xBF00FC00U) == 0x2F005400U) return Op{Family::SHIFT, 35, 5, "SLI"};
    if ((op & 0xBF00FC00U) == 0x2F004400U) return Op{Family::SHIFT, 36, 6, "SRI"};
    if ((op & 0xBF00FC00U) == 0x2F003400U) return Op{Family::SHIFT, 37, 7, "URSRA"};
    if ((op & 0xBF00FC00U) == 0x0F003400U) return Op{Family::SHIFT, 38, 8, "SRSRA"};
    if ((op & 0xBFE0FC00U) == 0x0E000C00U && ((((op >> 16) & 0x1F) == 1 || ((op >> 16) & 0x1F) == 2 || ((op >> 16) & 0x1F) == 4 || ((op >> 16) & 0x1F) == 8))) return Op{Family::DUP, 39, 0, "DUP"};
    if ((op & 0xBFE0FC00U) == 0x0E003C00U) return Op{Family::UMOV, 40, 0, "UMOV"};
    if ((op & 0xFFFFFC00U) == 0x4E284800U) return Op{Family::CRYPTO, 41, 0, "AESE"};
    if ((op & 0xFFE0FC00U) == 0x4E60E000U) return Op{Family::CRYPTO, 42, 4, "PMULL"};
    if ((op & 0xFFE0FC00U) == 0x4EE0E000U) return Op{Family::CRYPTO, 43, 5, "PMULL2"};
    if ((op & 0xBFE0FC00U) == 0x0E205800U) return Op{Family::PMISC, 44, 0, "CNT"};
    if ((op & 0xBFE0FC00U) == 0x2E205800U) return Op{Family::PMISC, 45, 1, "NOT"};
    if ((op & 0xBFE0FC00U) == 0x2E605800U) return Op{Family::PMISC, 46, 2, "RBIT"};
    if ((op & 0xBF21FC00U) == 0x0E20B800U) return Op{Family::PMISC, 47, 3, "ABS"};
    if ((op & 0xBF21FC00U) == 0x2E20B800U) return Op{Family::PMISC, 48, 4, "NEG"};
    if ((op & 0xBF20FC00U) == 0x0E20D800U && (size == 0)) return Op{Family::CVTF, 49, 0, "SCVTF"};
    if ((op & 0xBF20FC00U) == 0x2E20D800U && (size == 0)) return Op{Family::CVTF, 50, 1, "UCVTF"};
    if ((op & 0xBF21FC00U) == 0x0E21B800U && (size == 2)) return Op{Family::CVTF, 51, 2, "FCVTZS"};
    if ((op & 0xBF21FC00U) == 0x2E21B800U && (size == 2)) return Op{Family::CVTF, 52, 3, "FCVTZU"};
    if ((op & 0xBF20FC00U) == 0x0E20BC00U && (size == 0)) return Op{Family::ADDP, 53, 0, "ADDP"};
    if ((op & 0xBF20FC00U) == 0x0E202800U && (size < 3)) return Op{Family::XTN, 54, 0, "XTN"};
    if ((op & 0xBF20FC00U) == 0x2E202800U && (size < 3)) return Op{Family::XTN, 55, 1, "SQXTUN"};
    if ((op & 0xBF20FC00U) == 0x0E204800U && (size < 3)) return Op{Family::XTN, 56, 2, "SQXTN"};
    if ((op & 0xBF20FC00U) == 0x2E204800U && (size < 3)) return Op{Family::XTN, 57, 3, "UQXTN"};
    if ((op & 0xBFE0FC00U) == 0x0E000000U) return Op{Family::TBL, 58, 0, "TBL1"};
    if ((op & 0xBFE0FC00U) == 0x0E002000U) return Op{Family::TBL, 59, 1, "TBL2"};
    if ((op & 0xBFE0FC00U) == 0x0E001000U) return Op{Family::TBL, 60, 2, "TBX1"};
    if ((op & 0xBFE0FC00U) == 0x0E003000U) return Op{Family::TBL, 61, 3, "TBX2"};
    if ((op & 0xBFE00400U) == 0x2E000400U && (((op >> 16) & 0x0F) != 0)) return Op{Family::INS, 62, 0, "INS"};
    if ((op & 0x3F20FC00U) == 0x0E001800U && (Q || size != 3)) return Op{Family::PERMUTE, 63, 6, "UZP1"};
    if ((op & 0x3F20FC00U) == 0x0E002800U && (Q || size != 3)) return Op{Family::PERMUTE, 64, 10, "TRN1"};
    if ((op & 0x3F20FC00U) == 0x0E003800U && (Q || size != 3)) return Op{Family::PERMUTE, 65, 14, "ZIP1"};
    if ((op & 0x3F20FC00U) == 0x0E005800U && (Q || size != 3)) return Op{Family::PERMUTE, 66, 22, "UZP2"};
    if ((op & 0x3F20FC00U) == 0x0E006800U && (Q || size != 3)) return Op{Family::PERMUTE, 67, 26, "TRN2"};
    if ((op & 0x3F20FC00U) == 0x0E007800U && (Q || size != 3)) return Op{Family::PERMUTE, 68, 30, "ZIP2"};
    if ((op & 0x3F20FC00U) == 0x0E20A400U) return Op{Family::PAIRMIN, 69, 0, "SMAXP"};
    if ((op & 0x3F20FC00U) == 0x0E20AC00U) return Op{Family::PAIRMIN, 70, 1, "SMINP"};
    if ((op & 0x3F20FC00U) == 0x2E20A400U) return Op{Family::PAIRMIN, 71, 2, "UMAXP"};
    if ((op & 0x3F20FC00U) == 0x2E20AC00U) return Op{Family::PAIRMIN, 72, 3, "UMINP"};
    if ((op & 0xBF20FC00U) == 0x0E207000U) return Op{Family::ABDL, 73, 0, "SABDL"};
    if ((op & 0xBF20FC00U) == 0x2E207000U) return Op{Family::ABDL, 74, 1, "UABDL"};
    if ((op & 0xBF20FC00U) == 0x0E205000U) return Op{Family::ABDL, 75, 2, "SABAL"};
    if ((op & 0xBF20FC00U) == 0x2E205000U) return Op{Family::ABDL, 76, 3, "UABAL"};
    if ((op & 0xBF20FC00U) == 0x0E207400U) return Op{Family::ABD, 77, 0, "SABD"};
    if ((op & 0xBF20FC00U) == 0x2E207400U) return Op{Family::ABD, 78, 1, "UABD"};
    if ((op & 0xBF20FC00U) == 0x0E201000U && (size != 0 && size < 3)) return Op{Family::ADDW, 79, 0, "SADDW"};
    if ((op & 0xBF20FC00U) == 0x2E201000U && (size != 0 && size < 3)) return Op{Family::ADDW, 80, 1, "UADDW"};
    if ((op & 0xBF20FC00U) == 0x0E203000U && (size != 0 && size < 3)) return Op{Family::ADDW, 81, 2, "SSUBW"};
    if ((op & 0xBF20FC00U) == 0x2E203000U && (size != 0 && size < 3)) return Op{Family::ADDW, 82, 3, "USUBW"};
    if ((op & 0xBF20FC00U) == 0x0E204000U && (size < 3)) return Op{Family::ADDHN, 83, 0, "ADDHN"};
    if ((op & 0xBF20FC00U) == 0x2E204000U && (size < 3)) return Op{Family::ADDHN, 84, 1, "RADDHN"};
    if ((op & 0xBF20FC00U) == 0x0E206000U && (size < 3)) return Op{Family::ADDHN, 85, 2, "SUBHN"};
    if ((op & 0xBF20FC00U) == 0x2E206000U && (size < 3)) return Op{Family::ADDHN, 86, 3, "RSUBHN"};
    if ((op & 0xBF00FC00U) == 0x0F009400U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 87, 0, "SQSHRN"};
    if ((op & 0xBF00FC00U) == 0x2F009400U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 88, 1, "UQSHRN"};
    if ((op & 0xBF00FC00U) == 0x0F009C00U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 89, 2, "SQRSHRN"};
    if ((op & 0xBF00FC00U) == 0x2F009C00U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 90, 3, "URQSHRN"};
    if ((op & 0xBF00FC00U) == 0x2F008400U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 91, 4, "SQSHRUN"};
    if ((op & 0xBF00FC00U) == 0x2F008C00U && (((op >> 19) & 0xF) != 0)) return Op{Family::SHRN_SAT, 92, 5, "SQRSHRUN"};
    if ((op & 0xBF00F400U) == 0x0F008000U && (size < 3)) return Op{Family::MUL_ELEM, 93, 0, "MUL_ELEM"};
    if ((op & 0xBF00F400U) == 0x2F000000U && (size < 3)) return Op{Family::MUL_ELEM, 94, 1, "MLA_ELEM"};
    if ((op & 0xBF00F400U) == 0x2F004000U && (size < 3)) return Op{Family::MUL_ELEM, 95, 2, "MLS_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F00A000U && (size < 3)) return Op{Family::MUL_ELEM, 96, 3, "SMULL_ELEM"};
    if ((op & 0xBF00F400U) == 0x2F00A000U && (size < 3)) return Op{Family::MUL_ELEM, 97, 4, "UMULL_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F002000U && (size < 3)) return Op{Family::MUL_ELEM, 98, 5, "SMLAL_ELEM"};
    if ((op & 0xBF00F400U) == 0x2F002000U && (size < 3)) return Op{Family::MUL_ELEM, 99, 6, "UMLAL_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F006000U && (size < 3)) return Op{Family::MUL_ELEM, 100, 7, "SMLSL_ELEM"};
    if ((op & 0xBF00F400U) == 0x2F006000U && (size < 3)) return Op{Family::MUL_ELEM, 101, 8, "UMLSL_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F00C000U && (size < 3)) return Op{Family::MUL_ELEM, 102, 9, "SQDMULH_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F00D000U && (size < 3)) return Op{Family::MUL_ELEM, 103, 10, "SQRDMULH_ELEM"};
    if ((op & 0xBF00F400U) == 0x0F00B000U && (size < 3)) return Op{Family::MUL_ELEM, 104, 11, "SQDMULL_ELEM"};
    if ((op & 0xBFE0FC00U) == 0x0E002C00U && (((op >> 16) & 0x1F) == 1 || ((op >> 16) & 0x1F) == 2 || ((op >> 16) & 0x1F) == 4)) return Op{Family::SMOV, 105, 0, "SMOV"};
    if ((op & 0xBF20FC00U) == 0x0E200C00U && (size < 2)) return Op{Family::SATADDSUB, 106, 0, "SQADD"};
    if ((op & 0xBF20FC00U) == 0x2E200C00U && (size < 2)) return Op{Family::SATADDSUB, 107, 1, "UQADD"};
    if ((op & 0xBF20FC00U) == 0x0E202C00U && (size < 2)) return Op{Family::SATADDSUB, 108, 2, "SQSUB"};
    if ((op & 0xBF20FC00U) == 0x2E202C00U && (size < 2)) return Op{Family::SATADDSUB, 109, 3, "UQSUB"};
    if ((op & 0xBFBFFC00U) == 0x0EA0F800U && (Q || size == 2)) return Op{Family::FP_UNARY, 110, 0, "FABS_VEC"};
    if ((op & 0xBFBFFC00U) == 0x2EA0F800U && (Q || size == 2)) return Op{Family::FP_UNARY, 111, 1, "FNEG_VEC"};
    if ((op & 0xBFBFFC00U) == 0x2EA1F800U && (Q || size == 2)) return Op{Family::FP_UNARY, 112, 2, "FSQRT_VEC"};
    if ((op & 0xBF00F400U) == 0x0F009000U && (size >= 2 && (Q || size == 2) && (size == 2 || ((op >> 21) & 1) == 0))) return Op{Family::FP_INDEXED, 113, 2, "FMUL_INDEX"};
    return Op{Family::UNKNOWN, 0, 0, "unknown"};
}

} // namespace simd
} // namespace arm64emu
