// opgen_simd.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/opgen.py from tools/opgen/simd_dp.txt.
// To add/modify a SIMD opcode edit the spec and run: make opgen
//
// Single source of truth for SIMD_DP decode. The interpreter
// (interp_fp.cpp), the IR translator (ir_translate_fp.cpp) and the JIT
// block heuristic (jit_translate.cpp) all classify with
// arm64emu::simd::classify(), so the three copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace simd {

enum class Family : uint8_t {
    INT_ARITH = 0,
    INT_CMP = 1,
    LOGIC = 2,
    FP = 3,
    MODIMM = 4,
    SHIFT = 5,
    DUP = 6,
    UMOV = 7,
    CRYPTO = 8,
    UNKNOWN = 9,
};

struct Op {
    Family family;
    uint16_t opc;            // stable per-opcode id (row index in spec)
    uint8_t subop;           // per-family semantic sub-opcode (IRSUB)
    const char* name;
};

inline Op classify(uint32_t op) {
    const uint32_t Q    = (op >> 30) & 1u;
    const uint32_t U    = (op >> 29) & 1u;
    const uint32_t size = (op >> 22) & 3u;
    (void)U;
    if ((op & 0xBF20FC00U) == 0x0E208400U) return Op{Family::INT_ARITH, 0, 0, "ADD"};
    if ((op & 0xBF20FC00U) == 0x2E208400U) return Op{Family::INT_ARITH, 1, 1, "SUB"};
    if ((op & 0xBF20FC00U) == 0x0E209C00U && (size != 3)) return Op{Family::INT_ARITH, 2, 2, "MUL"};
    if ((op & 0xBF20FC00U) == 0x2E206C00U) return Op{Family::INT_ARITH, 3, 3, "UMIN"};
    if ((op & 0xBF20FC00U) == 0x2E206400U) return Op{Family::INT_ARITH, 4, 4, "UMAX"};
    if ((op & 0xBF20FC00U) == 0x0E206C00U) return Op{Family::INT_ARITH, 5, 5, "SMIN"};
    if ((op & 0xBF20FC00U) == 0x0E206400U) return Op{Family::INT_ARITH, 6, 6, "SMAX"};
    if ((op & 0xBF20FC00U) == 0x0E203400U) return Op{Family::INT_CMP, 7, 1, "CMGT"};
    if ((op & 0xBF20FC00U) == 0x0E203C00U) return Op{Family::INT_CMP, 8, 2, "CMGE"};
    if ((op & 0xBF20FC00U) == 0x2E208C00U) return Op{Family::INT_CMP, 9, 0, "CMEQ"};
    if ((op & 0xBF20FC00U) == 0x2E203400U) return Op{Family::INT_CMP, 10, 3, "CMHI"};
    if ((op & 0xBF20FC00U) == 0x2E203C00U) return Op{Family::INT_CMP, 11, 4, "CMHS"};
    if ((op & 0xBFE0FC00U) == 0x0E201C00U && (Q)) return Op{Family::LOGIC, 12, 0, "AND"};
    if ((op & 0xBFE0FC00U) == 0x0EA01C00U && (Q)) return Op{Family::LOGIC, 13, 1, "ORR"};
    if ((op & 0xBFE0FC00U) == 0x2E201C00U && (Q)) return Op{Family::LOGIC, 14, 2, "EOR"};
    if ((op & 0xBFE0FC00U) == 0x0E601C00U && (Q)) return Op{Family::LOGIC, 15, 3, "BIC"};
    if ((op & 0xBFE0FC00U) == 0x0EE01C00U && (Q)) return Op{Family::LOGIC, 16, 4, "ORN"};
    if ((op & 0xBFA0FC00U) == 0x0E20D400U) return Op{Family::FP, 17, 0, "FADD"};
    if ((op & 0xBFA0FC00U) == 0x0EA0D400U) return Op{Family::FP, 18, 1, "FSUB"};
    if ((op & 0xBFA0FC00U) == 0x2E20DC00U) return Op{Family::FP, 19, 2, "FMUL"};
    if ((op & 0xBFA0FC00U) == 0x2E20FC00U) return Op{Family::FP, 20, 3, "FDIV"};
    if ((op & 0xBFA0FC00U) == 0x0E20F400U) return Op{Family::FP, 21, 4, "FMAX"};
    if ((op & 0xBFA0FC00U) == 0x0EA0F400U) return Op{Family::FP, 22, 5, "FMIN"};
    if ((op & 0xBFA0FC00U) == 0x0E20C400U) return Op{Family::FP, 23, 6, "FMAXNM"};
    if ((op & 0xBFA0FC00U) == 0x0EA0C400U) return Op{Family::FP, 24, 7, "FMINNM"};
    if ((op & 0xBFA0FC00U) == 0x0E20DC00U) return Op{Family::FP, 25, 11, "FMULX"};
    if ((op & 0xBFA0FC00U) == 0x2EA0D400U) return Op{Family::FP, 26, 13, "FABD"};
    if ((op & 0xBFA0FC00U) == 0x0E20CC00U) return Op{Family::FP, 27, 14, "FMLA"};
    if ((op & 0xBFA0FC00U) == 0x0EA0CC00U) return Op{Family::FP, 28, 15, "FMLS"};
    if ((op & 0x9F800C00U) == 0x0F000400U && (((op >> 19) & 0xF) == 0)) return Op{Family::MODIMM, 29, 0, "MOVI"};
    if ((op & 0xBF00FC00U) == 0x0F005400U) return Op{Family::SHIFT, 30, 0, "SHL"};
    if ((op & 0xBF00FC00U) == 0x2F000400U) return Op{Family::SHIFT, 31, 1, "USHR"};
    if ((op & 0xBF00FC00U) == 0x0F000400U) return Op{Family::SHIFT, 32, 2, "SSHR"};
    if ((op & 0xBF00FC00U) == 0x2F001400U) return Op{Family::SHIFT, 33, 3, "USRA"};
    if ((op & 0xBF00FC00U) == 0x0F001400U) return Op{Family::SHIFT, 34, 4, "SSRA"};
    if ((op & 0xBF00FC00U) == 0x2F005400U) return Op{Family::SHIFT, 35, 5, "SLI"};
    if ((op & 0xBF00FC00U) == 0x2F004400U) return Op{Family::SHIFT, 36, 6, "SRI"};
    if ((op & 0xBF00FC00U) == 0x2F003400U) return Op{Family::SHIFT, 37, 7, "URSRA"};
    if ((op & 0xBF00FC00U) == 0x0F003400U) return Op{Family::SHIFT, 38, 8, "SRSRA"};
    if ((op & 0xBFE0FC00U) == 0x0E000C00U && ((((op >> 16) & 0x1F) == 1 || ((op >> 16) & 0x1F) == 2 || ((op >> 16) & 0x1F) == 4 || ((op >> 16) & 0x1F) == 8))) return Op{Family::DUP, 39, 0, "DUP"};
    if ((op & 0xBFE0FC00U) == 0x0E003C00U) return Op{Family::UMOV, 40, 0, "UMOV"};
    if ((op & 0xFFFFFC00U) == 0x4E284800U) return Op{Family::CRYPTO, 41, 0, "AESE"};
    if ((op & 0xFFE0FC00U) == 0x4E60E000U) return Op{Family::CRYPTO, 42, 4, "PMULL"};
    if ((op & 0xFFE0FC00U) == 0x4EE0E000U) return Op{Family::CRYPTO, 43, 5, "PMULL2"};
    return Op{Family::UNKNOWN, 0, 0, "unknown"};
}

} // namespace simd
} // namespace arm64emu
