// opgen_simd.hpp — GENERATED. DO NOT EDIT.
//
// Generated by tools/opgen/opgen.py from tools/opgen/simd_dp.txt.
// To add/modify a SIMD opcode edit the spec and run: make opgen
//
// Single source of truth for SIMD_DP decode. The interpreter
// (interp_fp.cpp), the IR translator (ir_translate_fp.cpp) and the JIT
// block heuristic (jit_translate.cpp) all classify with
// arm64emu::simd::classify(), so the three copies can no longer drift.
#pragma once
#include <cstdint>
#include <cstddef>

namespace arm64emu {
namespace simd {

enum class Family : uint8_t {
    INT_ARITH = 0,
    INT_CMP = 1,
    LOGIC = 2,
    FP = 3,
    MODIMM = 4,
    SHIFT = 5,
    DUP = 6,
    UMOV = 7,
    CRYPTO = 8,
    PMISC = 9,
    CVTF = 10,
    ADDP = 11,
    XTN = 12,
    TBL = 13,
    INS = 14,
    PERMUTE = 15,
    PAIRMIN = 16,
    UNKNOWN = 17,
};

struct Op {
    Family family;
    uint16_t opc;            // stable per-opcode id (row index in spec)
    uint8_t subop;           // per-family semantic sub-opcode (IRSUB)
    const char* name;
};

inline Op classify(uint32_t op) {
    const uint32_t Q    = (op >> 30) & 1u;
    const uint32_t U    = (op >> 29) & 1u;
    const uint32_t size = (op >> 22) & 3u;
    (void)U;
    if ((op & 0xBF20FC00U) == 0x0E208400U) return Op{Family::INT_ARITH, 0, 0, "ADD"};
    if ((op & 0xBF20FC00U) == 0x2E208400U) return Op{Family::INT_ARITH, 1, 1, "SUB"};
    if ((op & 0xBF20FC00U) == 0x0E209C00U && (size != 3)) return Op{Family::INT_ARITH, 2, 2, "MUL"};
    if ((op & 0xBF20FC00U) == 0x2E206C00U) return Op{Family::INT_ARITH, 3, 3, "UMIN"};
    if ((op & 0xBF20FC00U) == 0x2E206400U) return Op{Family::INT_ARITH, 4, 4, "UMAX"};
    if ((op & 0xBF20FC00U) == 0x0E206C00U) return Op{Family::INT_ARITH, 5, 5, "SMIN"};
    if ((op & 0xBF20FC00U) == 0x0E206400U) return Op{Family::INT_ARITH, 6, 6, "SMAX"};
    if ((op & 0xBF20FC00U) == 0x0E203400U) return Op{Family::INT_CMP, 7, 1, "CMGT"};
    if ((op & 0xBF20FC00U) == 0x0E203C00U) return Op{Family::INT_CMP, 8, 2, "CMGE"};
    if ((op & 0xBF20FC00U) == 0x2E208C00U) return Op{Family::INT_CMP, 9, 0, "CMEQ"};
    if ((op & 0xBF20FC00U) == 0x2E203400U) return Op{Family::INT_CMP, 10, 3, "CMHI"};
    if ((op & 0xBF20FC00U) == 0x2E203C00U) return Op{Family::INT_CMP, 11, 4, "CMHS"};
    if ((op & 0xBFE0FC00U) == 0x0E201C00U && (Q)) return Op{Family::LOGIC, 12, 0, "AND"};
    if ((op & 0xBFE0FC00U) == 0x0EA01C00U && (Q)) return Op{Family::LOGIC, 13, 1, "ORR"};
    if ((op & 0xBFE0FC00U) == 0x2E201C00U && (Q)) return Op{Family::LOGIC, 14, 2, "EOR"};
    if ((op & 0xBFE0FC00U) == 0x0E601C00U && (Q)) return Op{Family::LOGIC, 15, 3, "BIC"};
    if ((op & 0xBFE0FC00U) == 0x0EE01C00U && (Q)) return Op{Family::LOGIC, 16, 4, "ORN"};
    if ((op & 0xBFA0FC00U) == 0x0E20D400U) return Op{Family::FP, 17, 0, "FADD"};
    if ((op & 0xBFA0FC00U) == 0x0EA0D400U) return Op{Family::FP, 18, 1, "FSUB"};
    if ((op & 0xBFA0FC00U) == 0x2E20DC00U) return Op{Family::FP, 19, 2, "FMUL"};
    if ((op & 0xBFA0FC00U) == 0x2E20FC00U) return Op{Family::FP, 20, 3, "FDIV"};
    if ((op & 0xBFA0FC00U) == 0x0E20F400U) return Op{Family::FP, 21, 4, "FMAX"};
    if ((op & 0xBFA0FC00U) == 0x0EA0F400U) return Op{Family::FP, 22, 5, "FMIN"};
    if ((op & 0xBFA0FC00U) == 0x0E20C400U) return Op{Family::FP, 23, 6, "FMAXNM"};
    if ((op & 0xBFA0FC00U) == 0x0EA0C400U) return Op{Family::FP, 24, 7, "FMINNM"};
    if ((op & 0xBFA0FC00U) == 0x0E20DC00U) return Op{Family::FP, 25, 11, "FMULX"};
    if ((op & 0xBFA0FC00U) == 0x2EA0D400U) return Op{Family::FP, 26, 13, "FABD"};
    if ((op & 0xBFA0FC00U) == 0x0E20CC00U) return Op{Family::FP, 27, 14, "FMLA"};
    if ((op & 0xBFA0FC00U) == 0x0EA0CC00U) return Op{Family::FP, 28, 15, "FMLS"};
    if ((op & 0x9F800C00U) == 0x0F000400U && (((op >> 19) & 0xF) == 0)) return Op{Family::MODIMM, 29, 0, "MOVI"};
    if ((op & 0xBF00FC00U) == 0x0F005400U) return Op{Family::SHIFT, 30, 0, "SHL"};
    if ((op & 0xBF00FC00U) == 0x2F000400U) return Op{Family::SHIFT, 31, 1, "USHR"};
    if ((op & 0xBF00FC00U) == 0x0F000400U) return Op{Family::SHIFT, 32, 2, "SSHR"};
    if ((op & 0xBF00FC00U) == 0x2F001400U) return Op{Family::SHIFT, 33, 3, "USRA"};
    if ((op & 0xBF00FC00U) == 0x0F001400U) return Op{Family::SHIFT, 34, 4, "SSRA"};
    if ((op & 0xBF00FC00U) == 0x2F005400U) return Op{Family::SHIFT, 35, 5, "SLI"};
    if ((op & 0xBF00FC00U) == 0x2F004400U) return Op{Family::SHIFT, 36, 6, "SRI"};
    if ((op & 0xBF00FC00U) == 0x2F003400U) return Op{Family::SHIFT, 37, 7, "URSRA"};
    if ((op & 0xBF00FC00U) == 0x0F003400U) return Op{Family::SHIFT, 38, 8, "SRSRA"};
    if ((op & 0xBFE0FC00U) == 0x0E000C00U && ((((op >> 16) & 0x1F) == 1 || ((op >> 16) & 0x1F) == 2 || ((op >> 16) & 0x1F) == 4 || ((op >> 16) & 0x1F) == 8))) return Op{Family::DUP, 39, 0, "DUP"};
    if ((op & 0xBFE0FC00U) == 0x0E003C00U) return Op{Family::UMOV, 40, 0, "UMOV"};
    if ((op & 0xFFFFFC00U) == 0x4E284800U) return Op{Family::CRYPTO, 41, 0, "AESE"};
    if ((op & 0xFFE0FC00U) == 0x4E60E000U) return Op{Family::CRYPTO, 42, 4, "PMULL"};
    if ((op & 0xFFE0FC00U) == 0x4EE0E000U) return Op{Family::CRYPTO, 43, 5, "PMULL2"};
    if ((op & 0xBFE0FC00U) == 0x0E205800U) return Op{Family::PMISC, 44, 0, "CNT"};
    if ((op & 0xBFE0FC00U) == 0x2E205800U) return Op{Family::PMISC, 45, 1, "NOT"};
    if ((op & 0xBFE0FC00U) == 0x2E605800U) return Op{Family::PMISC, 46, 2, "RBIT"};
    if ((op & 0xBF21FC00U) == 0x0E20B800U) return Op{Family::PMISC, 47, 3, "ABS"};
    if ((op & 0xBF21FC00U) == 0x2E20B800U) return Op{Family::PMISC, 48, 4, "NEG"};
    if ((op & 0xBF20FC00U) == 0x0E20D800U && (size == 0)) return Op{Family::CVTF, 49, 0, "SCVTF"};
    if ((op & 0xBF20FC00U) == 0x2E20D800U && (size == 0)) return Op{Family::CVTF, 50, 1, "UCVTF"};
    if ((op & 0xBF21FC00U) == 0x0E21B800U && (size == 2)) return Op{Family::CVTF, 51, 2, "FCVTZS"};
    if ((op & 0xBF21FC00U) == 0x2E21B800U && (size == 2)) return Op{Family::CVTF, 52, 3, "FCVTZU"};
    if ((op & 0xBF20FC00U) == 0x0E20BC00U && (size == 0)) return Op{Family::ADDP, 53, 0, "ADDP"};
    if ((op & 0xBF20FC00U) == 0x0E202800U && (size < 3)) return Op{Family::XTN, 54, 0, "XTN"};
    if ((op & 0xBF20FC00U) == 0x2E202800U && (size < 3)) return Op{Family::XTN, 55, 1, "SQXTUN"};
    if ((op & 0xBF20FC00U) == 0x0E204800U && (size < 3)) return Op{Family::XTN, 56, 2, "SQXTN"};
    if ((op & 0xBF20FC00U) == 0x2E204800U && (size < 3)) return Op{Family::XTN, 57, 3, "UQXTN"};
    if ((op & 0xBFE0FC00U) == 0x0E000000U) return Op{Family::TBL, 58, 0, "TBL1"};
    if ((op & 0xBFE0FC00U) == 0x0E002000U) return Op{Family::TBL, 59, 1, "TBL2"};
    if ((op & 0xBFE0FC00U) == 0x0E001000U) return Op{Family::TBL, 60, 2, "TBX1"};
    if ((op & 0xBFE0FC00U) == 0x0E003000U) return Op{Family::TBL, 61, 3, "TBX2"};
    if ((op & 0xBFE00400U) == 0x2E000400U && (((op >> 16) & 0x0F) != 0)) return Op{Family::INS, 62, 0, "INS"};
    if ((op & 0x3F20FC00U) == 0x0E001800U && (Q || size != 3)) return Op{Family::PERMUTE, 63, 6, "UZP1"};
    if ((op & 0x3F20FC00U) == 0x0E002800U && (Q || size != 3)) return Op{Family::PERMUTE, 64, 10, "TRN1"};
    if ((op & 0x3F20FC00U) == 0x0E003800U && (Q || size != 3)) return Op{Family::PERMUTE, 65, 14, "ZIP1"};
    if ((op & 0x3F20FC00U) == 0x0E005800U && (Q || size != 3)) return Op{Family::PERMUTE, 66, 22, "UZP2"};
    if ((op & 0x3F20FC00U) == 0x0E006800U && (Q || size != 3)) return Op{Family::PERMUTE, 67, 26, "TRN2"};
    if ((op & 0x3F20FC00U) == 0x0E007800U && (Q || size != 3)) return Op{Family::PERMUTE, 68, 30, "ZIP2"};
    if ((op & 0x3F20FC00U) == 0x0E20A400U) return Op{Family::PAIRMIN, 69, 0, "SMAXP"};
    if ((op & 0x3F20FC00U) == 0x0E20AC00U) return Op{Family::PAIRMIN, 70, 1, "SMINP"};
    if ((op & 0x3F20FC00U) == 0x2E20A400U) return Op{Family::PAIRMIN, 71, 2, "UMAXP"};
    if ((op & 0x3F20FC00U) == 0x2E20AC00U) return Op{Family::PAIRMIN, 72, 3, "UMINP"};
    return Op{Family::UNKNOWN, 0, 0, "unknown"};
}

} // namespace simd
} // namespace arm64emu
